# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: tcptunnel CI (Go)

on:
  push:
    branches: [ "root" ]
  pull_request:
    branches: [ "root" ]
  workflow_dispatch:
    inputs:
      evironment:
        description: 'Application Environment'
        required: true
        default: 'LOCAL'
        type: choice
        options:
          - LOCAL
          - DEVELOP
          - PRODUCTION

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Select Environment ${{inputs.environment}}
      run: |
        source .env
        export APP_ENVIRONMENT="${{inputs.environment}}"

    - name: Build
      run: go build -v ./cmd/...

    - name: Test
      run: go test -v ./...
